import { Doctor, Service, Department, Testimonial, FAQItem, KenyaCity } from '@/types';

export const KENYAN_CITIES: KenyaCity[] = [
  {
    name: 'Nairobi',
    county: 'Nairobi',
    branchName: 'CarePlus Referral & Trauma Center',
    address: 'Upper Hill Medical Chambers, 4th Floor, Argwings Kodhek Road, Nairobi',
    phone: '+254 (0) 700 111 222',
    email: 'nairobi@careplus.co.ke',
    isMainClinic: true,
  },
  {
    name: 'Mombasa',
    county: 'Mombasa',
    branchName: 'CarePlus Coastal Clinic',
    address: 'Nyali Centre, Ground Floor, Links Road, Mombasa',
    phone: '+254 (0) 700 111 223',
    email: 'mombasa@careplus.co.ke',
    isMainClinic: false,
  },
  {
    name: 'Kisumu',
    county: 'Kisumu',
    branchName: 'CarePlus Lakeside Medical',
    address: 'Mega Plaza, 1st Floor, Oginga Odinga Street, Kisumu',
    phone: '+254 (0) 700 111 224',
    email: 'kisumu@careplus.co.ke',
    isMainClinic: false,
  },
  {
    name: 'Nakuru',
    county: 'Nakuru',
    branchName: 'CarePlus Rift Valley Clinic',
    address: 'Giddo Plaza, Block B, George Morara Avenue, Nakuru',
    phone: '+254 (0) 700 111 225',
    email: 'nakuru@careplus.co.ke',
    isMainClinic: false,
  },
  {
    name: 'Eldoret',
    county: 'Uasin Gishu',
    branchName: 'CarePlus Highlands Clinic',
    address: 'Elgon View Medical Center, Uganda Road, Eldoret',
    phone: '+254 (0) 700 111 226',
    email: 'eldoret@careplus.co.ke',
    isMainClinic: false,
  },
  {
    name: 'Ruiru',
    county: 'Kiambu',
    branchName: 'CarePlus Ruiru Medical Clinic',
    address: 'Spitfire Plaza, Ground Floor, Kamakis Bypass Road, Ruiru',
    phone: '+254 (0) 700 111 227',
    email: 'ruiru@careplus.co.ke',
    isMainClinic: false,
  },
  {
    name: 'Thika',
    county: 'Kiambu',
    branchName: 'CarePlus Thika Clinic',
    address: 'Zuri Towers, Kwame Nkrumah Road, Thika',
    phone: '+254 (0) 700 111 228',
    email: 'thika@careplus.co.ke',
    isMainClinic: false,
  },
  {
    name: 'Kikuyu',
    county: 'Kiambu',
    branchName: 'CarePlus Kikuyu Medical Center',
    address: 'Prestige Mall, Ground Floor, Southern Bypass, Kikuyu',
    phone: '+254 (0) 700 111 229',
    email: 'kikuyu@careplus.co.ke',
    isMainClinic: false,
  },
  {
    name: 'Naivasha',
    county: 'Nakuru',
    branchName: 'CarePlus Naivasha Clinic',
    address: 'Lakeview Heights, Moi South Lake Road, Naivasha',
    phone: '+254 (0) 700 111 230',
    email: 'naivasha@careplus.co.ke',
    isMainClinic: false,
  },
  {
    name: 'Nyeri',
    county: 'Nyeri',
    branchName: 'CarePlus Mount Kenya Clinic',
    address: 'Nyeri Heights Plaza, Gakere Road, Nyeri',
    phone: '+254 (0) 700 111 231',
    email: 'nyeri@careplus.co.ke',
    isMainClinic: false,
  },
  {
    name: 'Kakamega',
    county: 'Kakamega',
    branchName: 'CarePlus Western Hospital',
    address: 'Kakamega Town Mall, Kisumu-Kakamega Highway, Kakamega',
    phone: '+254 (0) 700 111 232',
    email: 'kakamega@careplus.co.ke',
    isMainClinic: false,
  },
  {
    name: 'Kisii',
    county: 'Kisii',
    branchName: 'CarePlus South Nyanza Clinic',
    address: 'Ouru Plaza, Hospital Road, Kisii',
    phone: '+254 (0) 700 111 233',
    email: 'kisii@careplus.co.ke',
    isMainClinic: false,
  },
  {
    name: 'Meru',
    county: 'Meru',
    branchName: 'CarePlus Meru Clinic',
    address: 'Meru West Mall, Tom Mboya Street, Meru',
    phone: '+254 (0) 700 111 234',
    email: 'meru@careplus.co.ke',
    isMainClinic: false,
  },
];

export const DOCTORS: Doctor[] = [
  {
    id: 'doc-1',
    name: 'Dr. Arthur Mwangi',
    specialty: 'Senior Cardiologist',
    experience: 18,
    availability: 'Mon - Fri (08:00 AM - 04:00 PM)',
    image: 'Mwangi',
    bio: 'Dr. Arthur Mwangi is a world-renowned interventional cardiologist with over 18 years of clinical experience. He specializes in the treatment of coronary artery disease, complex arrhythmias, and hypertensive emergencies.',
    education: 'Bachelor of Medicine & Surgery (UoN), Fellowship in Interventional Cardiology (University of Cape Town)',
    languages: ['English', 'Swahili'],
  },
  {
    id: 'doc-2',
    name: 'Dr. Amina Omondi',
    specialty: 'Lead Pediatrician',
    experience: 12,
    availability: 'Tue - Sat (09:00 AM - 05:00 PM)',
    image: 'Omondi',
    bio: 'Dr. Amina Omondi offers compassionate and comprehensive pediatric care for children of all ages. She is passionate about preventive pediatrics, immunizations, and children\'s nutritional health.',
    education: 'Bachelor of Medicine & Surgery (Moi University), Master of Medicine in Paediatrics (Makerere University)',
    languages: ['English', 'Swahili', 'Luo'],
  },
  {
    id: 'doc-3',
    name: 'Dr. Sarah Kerubo',
    specialty: 'Chief Dental Surgeon',
    experience: 9,
    availability: 'Mon - Thu (08:30 AM - 04:30 PM)',
    image: 'Kerubo',
    bio: 'Dr. Sarah Kerubo is committed to giving patients the perfect smile. She specializes in preventive care, advanced root canals, aesthetic fillings, and orthodontic procedures.',
    education: 'Bachelor of Dental Surgery (UoN), Master of Clinical Dentistry (University of the Witwatersrand)',
    languages: ['English', 'Swahili', 'Kisii'],
  },
  {
    id: 'doc-4',
    name: 'Dr. David Kiprop',
    specialty: 'General Physician',
    experience: 14,
    availability: '24/7 (Emergency Shift Rotation)',
    image: 'Kiprop',
    bio: 'Dr. David Kiprop is our chief emergency medicine expert and diagnostic physician. With 14 years of emergency room experience, he coordinates rapid trauma care and diagnostic triage.',
    education: 'Bachelor of Medicine & Surgery (Kenyatta University), Master of Medicine in Internal Medicine (UoN)',
    languages: ['English', 'Swahili', 'Kalenjin'],
  },
];

export const SERVICES: Service[] = [
  {
    id: 'srv-1',
    title: 'General Consultation',
    description: 'Comprehensive physical evaluations, chronic condition tracking, and personalized treatment plans.',
    detailedDescription: 'Our primary care services offer thorough diagnostic evaluations, annual physicals, disease management, and guidance for long-term healthy living. We ensure early detection of chronic conditions like hypertension and diabetes.',
    iconName: 'Activity',
  },
  {
    id: 'srv-2',
    title: 'Pediatrics',
    description: 'Specialized healthcare, scheduled immunizations, and developmental reviews for infants and children.',
    detailedDescription: 'Dedicated to pediatric care, we provide routine physical checks, growth and development monitoring, childhood immunizations, nutritional advice, and treatment for pediatric infections in a friendly environment.',
    iconName: 'Baby',
  },
  {
    id: 'srv-3',
    title: 'Cardiology',
    description: 'Expert cardiac screening, ECG, stress tests, and specialized management of high blood pressure.',
    detailedDescription: 'Our cardiovascular unit handles early screening and intervention for coronary heart disease, structural heart problems, arrhythmias, and offers state-of-the-art electrocardiograms and lifestyle consultations.',
    iconName: 'Heart',
  },
  {
    id: 'srv-4',
    title: 'Dental Care',
    description: 'Preventive cleanings, root canal therapy, tooth restorations, and cosmetic dental procedures.',
    detailedDescription: 'Providing complete oral health care including deep scale cleanings, aesthetic crowns, tooth extractions, root canal therapy, and standard fillings, using state-of-the-art dental equipment.',
    iconName: 'Sparkles',
  },
  {
    id: 'srv-5',
    title: 'Laboratory',
    description: 'On-site pathology, clinical biochemistry, and rapid diagnostic testing with accurate reporting.',
    detailedDescription: 'Our high-capacity laboratory is accredited to perform complex blood chemistry panels, hematology, microbiology, endocrinology, and regular wellness profiling with fast turnaround times.',
    iconName: 'FlaskConical',
  },
  {
    id: 'srv-6',
    title: 'Pharmacy',
    description: 'Fully certified pharmacy providing genuine prescription medications and patient advisory.',
    detailedDescription: 'The CarePlus licensed pharmacy carries certified medicines, chronic medication refills, and OTC medical supplies. Our pharmacists offer accurate drug guidance and counseling on dosage management.',
    iconName: 'FileText',
  },
];

export const DEPARTMENTS: Department[] = [
  {
    id: 'dep-1',
    name: 'Emergency Room',
    description: 'Fully equipped trauma bays with dedicated ambulances operating 24/7 for acute medical crises.',
    iconName: 'Flame',
    branches: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret'],
  },
  {
    id: 'dep-2',
    name: 'General Surgery',
    description: 'Accredited modular surgical suites for both minimally invasive and major complex operations.',
    iconName: 'Scissors',
    branches: ['Nairobi', 'Mombasa', 'Kisumu'],
  },
  {
    id: 'dep-3',
    name: 'Radiology',
    description: 'State-of-the-art digital X-ray machines, high-frequency ultrasounds, multi-slice CT, and MRI scanners.',
    iconName: 'ScanFace',
    branches: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret', 'Ruiru'],
  },
  {
    id: 'dep-4',
    name: 'Pediatrics Clinic',
    description: 'Child-friendly clinical wards dedicated to gentle pediatric examinations and adolescent health.',
    iconName: 'Baby',
    branches: ['All Branches'],
  },
  {
    id: 'dep-5',
    name: 'Maternity Suites',
    description: 'Safe birthing clinics, dedicated fetal monitors, and specialized infant intensive care (NICU).',
    iconName: 'HeartHandshake',
    branches: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru'],
  },
  {
    id: 'dep-6',
    name: 'Orthopedics',
    description: 'Surgical and non-surgical restoration of joint diseases, spine disorders, and bone fractures.',
    iconName: 'Accessibility',
    branches: ['Nairobi', 'Mombasa', 'Eldoret'],
  },
  {
    id: 'dep-7',
    name: 'Laboratory Medicine',
    description: 'Accredited pathology labs conducting high-precision chemical and genetic diagnostic testing.',
    iconName: 'FlaskConical',
    branches: ['All Branches'],
  },
  {
    id: 'dep-8',
    name: 'Intensive Care Unit',
    description: 'High-dependency intensive care suites with persistent cardiac support and ventilator technology.',
    iconName: 'HeartPulse',
    branches: ['Nairobi', 'Mombasa', 'Kisumu'],
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't-1',
    name: 'Emily Wambua',
    serviceReceived: 'Cardiology Services',
    rating: 5,
    review: 'The cardiology team at the Upper Hill branch in Nairobi saved my life. Dr. Arthur Mwangi diagnosed my arterial blockages immediately and set up a treatment plan that worked wonders. The nursing care was extremely professional, and the facility was clean and welcoming.',
    city: 'Nairobi',
  },
  {
    id: 't-2',
    name: 'John Kiprotich',
    serviceReceived: 'Pediatrics Care',
    rating: 5,
    review: 'Our baby had a high fever in the middle of the night. We rushed him to CarePlus Highlands Clinic in Eldoret. The emergency response was incredibly fast, and Dr. Amina Omondi followed up the next morning to ensure he was fully recovered. Excellent pediatric care!',
    city: 'Eldoret',
  },
  {
    id: 't-3',
    name: 'Asha Mohamed',
    serviceReceived: 'General Consultation & Pharmacy',
    rating: 5,
    review: 'I regularly visit CarePlus Coastal Clinic in Nyali, Mombasa for hypertension monitoring. The services are seamless. I book my appointment online, meet Dr. Kiprop with zero wait time, and pick my authentic medication at their licensed pharmacy with full guidance.',
    city: 'Mombasa',
  },
];

export const INSURANCE_PARTNERS = [
  { name: 'NHIF / SHA', description: 'National Health Insurance Fund / Social Health Authority' },
  { name: 'Jubilee Insurance', description: 'Corporate and Individual Premium Cover' },
  { name: 'UAP Old Mutual', description: 'Comprehensive Inpatient and Outpatient Cover' },
  { name: 'CIC Insurance', description: 'SME and Family Healthcare Solutions' },
  { name: 'Britam Health', description: 'Affordable Managed Care and Preventive Packages' },
  { name: 'APA Insurance', description: 'Premium Medical Cover across all branches' },
  { name: 'Madison Health', description: 'Corporate medical schemes accepted' },
  { name: 'Heritage Insurance', description: 'Full executive physical check-ups and surgeries' },
];

export const FAQS: FAQItem[] = [
  {
    id: 'faq-1',
    question: 'How do I book a doctor appointment online at CarePlus?',
    answer: 'Booking an appointment is simple. Click on the "Book Appointment" button on our navigation bar or landing sections. Fill in your full name, phone number, choose your preferred Kenyan city clinic, select the medical specialty/doctor, and pick a convenient date and time. You will receive an immediate SMS and email confirmation.',
    category: 'Appointments',
  },
  {
    id: 'faq-2',
    question: 'Which insurance plans are accepted at CarePlus clinics?',
    answer: 'We accept a wide range of local and international insurance providers in Kenya, including NHIF / SHA (Social Health Authority), Jubilee Insurance, UAP Old Mutual, CIC Insurance, Britam, APA Insurance, Madison, and Heritage. We also accept corporate covers. Please bring your active insurance card and national identity card during your clinic visit.',
    category: 'Insurance',
  },
  {
    id: 'faq-3',
    question: 'Do you offer emergency ambulance services, and how can I reach you?',
    answer: 'Yes, we provide 24/7 emergency response and ambulance services. You can reach our dedicated emergency dispatch team directly at +254 (0) 700 111 222 (Nairobi Central) or call your closest city branch. Our emergency services include fully-equipped ambulances with certified paramedics.',
    category: 'Emergency care',
  },
  {
    id: 'faq-4',
    question: 'What are the operating hours of CarePlus Medical Center clinics?',
    answer: 'Our Main Referral Centers in Nairobi, Mombasa, and Kisumu are open 24 hours a day, 7 days a week, including weekends and public holidays, for emergency, pharmacy, and laboratory services. Outpatient specialized clinics (such as Dental, Cardiology, and Pediatrics) operate Monday to Saturday from 8:00 AM to 6:00 PM.',
    category: 'Operating hours',
  },
  {
    id: 'faq-5',
    question: 'Do I need a referral letter to book a specialized consultation?',
    answer: 'No referral letter is required to see our specialists. You can book an appointment directly with any of our consultants, including Dr. Arthur Mwangi (Cardiologist), Dr. Amina Omondi (Pediatrician), or our dental surgeons, via our web portal or by calling our helpdesk.',
    category: 'Specialist referrals',
  },
  {
    id: 'faq-6',
    question: 'Are laboratory and diagnostic results available online?',
    answer: 'Yes, CarePlus provides secure digital delivery of diagnostic results. Once our accredited laboratory processes your samples, your report is securely emailed to you or accessible via our secure patient portal. Your consulting doctor will also review them with you.',
    category: 'Laboratory services',
  },
  {
    id: 'faq-7',
    question: 'Do you offer telemedicine consultations for remote patients in Kenya?',
    answer: 'Yes, CarePlus offers video-based telemedicine consultations for non-emergency primary care, chronic disease reviews, and prescription refilling. This service is ideal for patients residing in remote areas or those needing follow-up reviews. You can book a virtual session through our standard booking form.',
    category: 'Telemedicine',
  },
  {
    id: 'faq-8',
    question: 'Can I refill my chronic prescriptions directly from the CarePlus pharmacy?',
    answer: 'Absolutely. You can request a prescription refill by uploading your active CarePlus doctor note or booking a quick phone consultation. We also offer home/office delivery of prescription medications within Nairobi, Mombasa, and Kisumu cities.',
    category: 'Prescriptions',
  },
];
